/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLySinhVienUI;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.ThiSinh;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Collections;
import java.util.Vector;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author phamquanglong51
 */
public class QLTS_Nhom3 extends javax.swing.JFrame {

    PreparedStatement pst = null;
    JFrame frame = new JFrame();
    DefaultTableModel tableModel;
    ArrayList<ThiSinh> alist = new ArrayList<>();
    public String[] data;
//    XSSFWorkbook wb = new XSSFWorkbook();
//    XSSFSheet sheet;
//    XSSFSheet mainSheet = wb.sheet("Thí sinh");
//    XSSFSheet sheetA = wb.createSheet("Khối A");
//    XSSFSheet sheetB = wb.createSheet("Khối B");
//    XSSFSheet sheetC = wb.createSheet("Khối C");
    XSSFSheet[] exList;
    int tongSo;

    public QLTS_Nhom3() {
    }

    /**
     * Creates new form QLTS_Nhom3
     */
    public void databaseToArrayList() {
        alist.clear();
        try {
            Connection con = DBConnection.getConnection();
            String sql = "Select * from `thisinh`";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            //tableModel = (DefaultTableModel) table.getModel();
            while (rs.next()) {
                String SBD = rs.getString(1);
                String hoTen = rs.getString(2);
                String diaChi = rs.getString(3);
                String uuTien = rs.getString(4);
                String khoiThi = rs.getString(5);
                //tableModel.addRow(new Object[]{SBD, hoTen, diaChi, uuTien, khoiThi});
                ThiSinh ts = new ThiSinh(SBD, hoTen, diaChi, uuTien, khoiThi);
                alist.add(ts);
            }
            tongSo = alist.size();
        } catch (SQLException ex) {
            Logger.getLogger(QLTS_Nhom3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ArrayListToTable() {
        tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        for (int i = 0; i < alist.size(); i++) {
            Vector v = new Vector();
            v.add(alist.get(i).getSBD());
            v.add(alist.get(i).getHoTen());
            v.add(alist.get(i).getDiaChi());
            v.add(alist.get(i).getUuTien());
            v.add(alist.get(i).getKhoiThi());
            tableModel.addRow(v);
        }
    }

    public QLTS_Nhom3(String[] data) {
        this.data = data;
        if (data[0].contains("user")) {
            initComponents();
            btnThemThiSinhMoi.setVisible(false);
            btnSua.setVisible(false);
            btnXoa.setVisible(false);
            txtLoaiTK.setText("Người dùng");
            btnExcel.setVisible(false);
<<<<<<< HEAD
=======
            btnQuanLyTaiKhoan.setVisible(false);
>>>>>>> NhatMinh
            btnDangKyDuThi.setBackground(new Colors().getPrimaryColor());
        } else {
            initComponents();
            btnThemThiSinhMoi.setBackground(new Colors().getPrimaryColor());
            btnSua.setBackground(new Colors().getWarning());
            btnXoa.setBackground(new Colors().getDanger());
            txtLoaiTK.setText("Quản trị viên");
            btnDangKyDuThi.setVisible(false);
<<<<<<< HEAD
=======
            btnQuanLyTaiKhoan.setBackground(new Colors().getPrimaryColor());
>>>>>>> NhatMinh
        }
        txtTenTK.setText(data[1]);

        this.setLocationRelativeTo(null);
        btnTatCaThiSinh.setBackground(new Colors().getPrimaryColor());
        btnA.setBackground(new Colors().getPrimaryColor());
        btnB.setBackground(new Colors().getPrimaryColor());
        btnC.setBackground(new Colors().getPrimaryColor());
        btnD.setBackground(new Colors().getPrimaryColor());
        btnXemMonThi.setBackground(new Colors().getPrimaryColor());

        label.setForeground(new Colors().getPrimaryColor());

        databaseToArrayList();
        ArrayListToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnA = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnTatCaThiSinh = new javax.swing.JButton();
        btnXemMonThi = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnQuanLyTaiKhoan = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnThemThiSinhMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLoaiTK = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbSapXep = new javax.swing.JComboBox<>();
        btnInfo = new javax.swing.JButton();
        btnDangKyDuThi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhóm 3 - Quản lý tuyển sinh");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnA.setForeground(new java.awt.Color(255, 255, 255));
        btnA.setText("Thí sinh khối A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("Thí sinh khối C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnB.setForeground(new java.awt.Color(255, 255, 255));
        btnB.setText("Thí sinh khối B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnTatCaThiSinh.setForeground(new java.awt.Color(255, 255, 255));
        btnTatCaThiSinh.setText("Tất cả thí sinh");
        btnTatCaThiSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatCaThiSinhActionPerformed(evt);
            }
        });

        btnXemMonThi.setForeground(new java.awt.Color(255, 255, 255));
        btnXemMonThi.setText("Xem môn thi");
        btnXemMonThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemMonThiActionPerformed(evt);
            }
        });

        btnExcel.setText("Xuất ra Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnD.setForeground(new java.awt.Color(255, 255, 255));
        btnD.setText("Thí sinh khối D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnQuanLyTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyTaiKhoan.setText("Quản lý tài khoản");
        btnQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btnB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTatCaThiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemMonThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnTatCaThiSinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemMonThi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(btnExcel)
                .addContainerGap())
        );

        label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label.setText("Quản lý tuyển sinh đại học năm 2022");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số báo danh", "Họ tên", "Địa chỉ", "Ưu tiên", "Khối dự thi"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnThemThiSinhMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemThiSinhMoi.setText("Thêm thí sinh mới");
        btnThemThiSinhMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThiSinhMoiActionPerformed(evt);
            }
        });

        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên tài khoản:");

        jLabel2.setText("Loại tài khoản:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(584, 518));
        jButton1.setMinimumSize(new java.awt.Dimension(584, 518));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tìm kiếm thí sinh theo số báo danh:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search (2).png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Sắp xếp theo số báo danh", "Sắp xếp theo tên", "Sắp xếp theo địa chỉ", "Sắp xếp theo khối dự thi" }));
        cbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSapXepActionPerformed(evt);
            }
        });

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnDangKyDuThi.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKyDuThi.setText("Đăng ký dự thi");
        btnDangKyDuThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyDuThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemThiSinhMoi)
                                .addGap(50, 50, 50)
                                .addComponent(btnDangKyDuThi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDangKyDuThi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInfo)
                            .addComponent(label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(cbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemThiSinhMoi)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnDangKyDuThi))))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemThiSinhMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThiSinhMoiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ThemThiSinhMoiUI themThiSinhMoiUI = new ThemThiSinhMoiUI(data);
        themThiSinhMoiUI.setLocationRelativeTo(null);
        themThiSinhMoiUI.setVisible(true);
    }//GEN-LAST:event_btnThemThiSinhMoiActionPerformed

    public void sortByKhoi(String khoi) {
        alist = new ArrayList<>();
//        if (khoi.equals("Khối A")) sheet = sheetA;
//        else if (khoi.equals("Khối B")) sheet = sheetB;
//        else if (khoi.equals("Khối C")) sheet = sheetC;
        try {
            Connection con = DBConnection.getConnection();
//            tableModel.setRowCount(0);
//            tableModel = (DefaultTableModel) table.getModel();
            String sql = "Select * from thisinh where khoi = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, khoi);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String SBD = rs.getString(1);
                String hoTen = rs.getString(2);
                String diaChi = rs.getString(3);
                String uuTien = rs.getString(4);
                String khoiThi = rs.getString(5);
//                tableModel.addRow(new Object[]{SBD, hoTen, diaChi, uuTien, khoiThi});
                ThiSinh ts = new ThiSinh(SBD, hoTen, diaChi, uuTien, khoiThi);
                alist.add(ts);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLTS_Nhom3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        sortByKhoi("Khối A");
        ArrayListToTable();
    }//GEN-LAST:event_btnAActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (table.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(frame, "Chọn thí sinh cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            this.dispose();
            SuaThongTinThiSinhUI suaThongTinThiSinhUI = new SuaThongTinThiSinhUI(table.getValueAt(table.getSelectedRow(), 0).toString(), data);
            suaThongTinThiSinhUI.setLocationRelativeTo(null);
            suaThongTinThiSinhUI.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        if (table.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(frame, "Chọn thí sinh cần xoá", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Connection con = DBConnection.getConnection();
                String sql = "DELETE FROM `thisinh` WHERE SBD = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1, table.getValueAt(table.getSelectedRow(), 0).toString());

                int click = JOptionPane.showConfirmDialog(frame, "Bạn có chắc muốn xoá thí sinh " + table.getValueAt(table.getSelectedRow(), 0).toString() + ""
                        + " không?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (click == JOptionPane.YES_OPTION) {
                    pst.executeUpdate();
                    tableModel.setRowCount(0);
                    String sql2 = "Select * from `thisinh`";
                    pst = con.prepareStatement(sql2);
                    ResultSet rs = pst.executeQuery();
                    tableModel = (DefaultTableModel) table.getModel();
                    while (rs.next()) {
                        tableModel.addRow(new Object[]{
                            rs.getString(1),
                            rs.getString(2),
                            rs.getString(3),
                            rs.getString(4),
                            rs.getString(5)
                        });
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLTS_Nhom3.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(frame, "Bạn có chắc muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (click == JOptionPane.YES_OPTION) {
            this.dispose();
            DangNhapUI loginUI = new DangNhapUI();
            loginUI.setLocationRelativeTo(null);
            loginUI.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        sortByKhoi("Khối B");
        ArrayListToTable();
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        sortByKhoi("Khối C");
        ArrayListToTable();
    }//GEN-LAST:event_btnCActionPerformed

    private void btnTatCaThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatCaThiSinhActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        databaseToArrayList();
        ArrayListToTable();
//        sheet = mainSheet;
    }//GEN-LAST:event_btnTatCaThiSinhActionPerformed

    private void btnXemMonThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemMonThiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        XemMonThiUI xemMonThiUI = new XemMonThiUI(data);
        xemMonThiUI.setLocationRelativeTo(null);
        xemMonThiUI.setVisible(true);
    }//GEN-LAST:event_btnXemMonThiActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    public void search(String text) {
        try {
            Connection con = DBConnection.getConnection();
            tableModel.setRowCount(0);
            tableModel = (DefaultTableModel) table.getModel();
            String sql = "Select * from thisinh where SBD = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, text);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(QLTS_Nhom3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search(txtSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed
    private void ListToExcel(XSSFWorkbook wb, XSSFSheet Sheet) {
        try {
            int i;
            XSSFRow row = null;
            Cell cell = null;
            row = Sheet.createRow(2);
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tổng số: " + alist.size());

            row = Sheet.createRow(3);
            //Header
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("SBD");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Họ tên");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Địa chỉ");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ưu tiên");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Khối thi");

            for (i = 0; i < alist.size(); i++) {
                row = Sheet.createRow(4 + i);

                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(alist.get(i).getSBD());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(alist.get(i).getHoTen());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(alist.get(i).getDiaChi());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(alist.get(i).getUuTien());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(alist.get(i).getKhoiThi());

            }
            float t = (float) alist.size() / tongSo * 100;
            row = Sheet.createRow(5 + i);
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue(t + "%");
            File f = new File("thisinh.xlsx");
            try {
                FileOutputStream fos = new FileOutputStream(f);
                wb.write(fos);
                fos.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet sheet = wb.createSheet("Thí sinh");
        databaseToArrayList();
        ListToExcel(wb, sheet);
        sheet = wb.createSheet("Khối A");
        sortByKhoi("Khối A");
        ListToExcel(wb, sheet);
        sheet = wb.createSheet("Khối B");
        sortByKhoi("Khối B");
        ListToExcel(wb, sheet);
        sheet = wb.createSheet("Khối C");
        sortByKhoi("Khối C");
        ListToExcel(wb, sheet);
        JOptionPane.showMessageDialog(this, "Xuất file excel thành công");

    }//GEN-LAST:event_btnExcelActionPerformed

    public void SapXep() {
        tableModel.setRowCount(0);
        for (int i = 0; i < alist.size(); i++) {
            tableModel.addRow(new Object[]{
                alist.get(i).getSBD(),
                alist.get(i).getHoTen(),
                alist.get(i).getDiaChi(),
                alist.get(i).getUuTien(),
                alist.get(i).getKhoiThi()
            });
        }
    }
    private void cbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSapXepActionPerformed
        // TODO add your handling code here:
        switch (cbSapXep.getSelectedItem().toString()) {
            case "Sắp xếp theo số báo danh":
                Collections.sort(alist, (o1, o2) -> o2.getSBD().compareTo(o1.getSBD()));
                Collections.reverse(alist);
                SapXep();
                break;
            case "Sắp xếp theo tên":
                Collections.sort(alist, (o1, o2) -> o1.getHoTen().compareTo(o2.getHoTen()));
                SapXep();
                break;
            case "Sắp xếp theo địa chỉ":
                Collections.sort(alist, (o1, o2) -> o1.getDiaChi().compareTo(o2.getDiaChi()));
                SapXep();
                break;
            case "Sắp xếp theo khối dự thi":
                Collections.sort(alist, (o1, o2) -> o1.getKhoiThi().compareTo(o2.getKhoiThi()));
                SapXep();
                break;
            case "--":
                SapXep();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_cbSapXepActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
        sortByKhoi("Khối D");
        ArrayListToTable();
    }//GEN-LAST:event_btnDActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        InfoUI infoUI = new InfoUI(data);
        infoUI.setLocationRelativeTo(null);
        infoUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnDangKyDuThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyDuThiActionPerformed
        // TODO add your handling code here:
        this.dispose();
<<<<<<< HEAD
        new ThemThiSinhMoiUI(data).setVisible(true);
    }//GEN-LAST:event_btnDangKyDuThiActionPerformed

=======
        ThemThiSinhMoiUI themThiSinhMoiUI = new ThemThiSinhMoiUI(data);
        themThiSinhMoiUI.setLocationRelativeTo(null);
        themThiSinhMoiUI.setVisible(true);
    }//GEN-LAST:event_btnDangKyDuThiActionPerformed

    private void btnQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QuanLyTaiKhoanUI(data).setVisible(true);
    }//GEN-LAST:event_btnQuanLyTaiKhoanActionPerformed

>>>>>>> NhatMinh
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTS_Nhom3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTS_Nhom3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTS_Nhom3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTS_Nhom3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLTS_Nhom3 QLTS = new QLTS_Nhom3();
                QLTS.setLocationRelativeTo(null);
                QLTS.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDangKyDuThi;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JButton btnSearch;
    public javax.swing.JButton btnSua;
    private javax.swing.JButton btnTatCaThiSinh;
    public javax.swing.JButton btnThemThiSinhMoi;
    private javax.swing.JButton btnXemMonThi;
    public javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbSapXep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable table;
    public javax.swing.JLabel txtLoaiTK;
    private javax.swing.JTextField txtSearch;
    public javax.swing.JLabel txtTenTK;
    // End of variables declaration//GEN-END:variables
}
