/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLySinhVienUI;

import Model.TaiKhoan;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamquanglong51
 */
public class QuanLyTaiKhoanUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTaiKhoanUI
     */
    JFrame frame = new JFrame();
    public String[] data;
    ArrayList<TaiKhoan> tkList = new ArrayList<>();
    DefaultTableModel tableModel;
    public QuanLyTaiKhoanUI(String[] data) {
        initComponents();
        this.setLocationRelativeTo(null);
        label.setForeground(new Colors().getPrimaryColor());
        btnXoa.setBackground(new Colors().getDanger());
        btnThayDoiQuyenTruyCap.setBackground(new Colors().getWarning());
        this.data = data;
        loadTable();
    }

    public QuanLyTaiKhoanUI() {
        
    }
    public void loadTable(){
        fileToArray();
        ArrayListToTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnThayDoiQuyenTruyCap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tài khoản");

        label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label.setText("Quản lý tài khoản");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quyền truy cập", "Tên tài khoản"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThayDoiQuyenTruyCap.setForeground(new java.awt.Color(255, 255, 255));
        btnThayDoiQuyenTruyCap.setText("Thay đổi quyền truy cập");
        btnThayDoiQuyenTruyCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiQuyenTruyCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThayDoiQuyenTruyCap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnThayDoiQuyenTruyCap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QLTS_Nhom3(data).setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThayDoiQuyenTruyCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiQuyenTruyCapActionPerformed
        // TODO add your handling code here:
        if (table.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(frame, "Chọn thí sinh cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            String typeSelected = table.getValueAt(table.getSelectedRow(), 0).toString();
            if (typeSelected.equals("user")) {
                tkList.get(table.getSelectedRow()).setType("admin");
            } else {
                tkList.get(table.getSelectedRow()).setType("user");
            }
            updateFile(tkList);
            loadTable();
        }
        
    }//GEN-LAST:event_btnThayDoiQuyenTruyCapActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (table.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(frame, "Chọn tài khoản cần xoá", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            tkList.remove(table.getSelectedRow());
        updateFile(tkList);
        loadTable();
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed
    public void updateFile(ArrayList<TaiKhoan> alist){
          FileWriter fw = null;
                BufferedWriter bw = null;
                FileReader fr = null;
                BufferedReader br = null;
                try {
                    fw = new FileWriter("user.txt");
                    bw = new BufferedWriter(fw);
                    fr = new FileReader("user.txt");
                    br = new BufferedReader(fr);
                    for (int i = 0; i < tkList.size(); i++) {
                        String temp = alist.get(i).getType() + "$" + alist.get(i).getUserName()+ "$" + alist.get(i).getPassWord();
                        String encodedString = Base64.getEncoder().encodeToString(temp.getBytes());
                        bw.append(encodedString);
                        bw.newLine();
                    }
                        
                   
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(frame, e);
                } finally {
                    try {
                        bw.close();
                        br.close();
                        fw.close();
                        fr.close();
                    } catch (IOException ex) {
                        Logger.getLogger(QuanLyTaiKhoanUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    }
    public void fileToArray() {
        tkList.clear();
        int i=0;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            fr = new FileReader("user.txt");
            br = new BufferedReader(fr);
            String check = null;
            while ((check = br.readLine()) != null) {
                byte[] decodedBytes = Base64.getDecoder().decode(check);
                String decodedString = new String(decodedBytes);
                String obj[] = decodedString.split("\\$");
                TaiKhoan tk = new TaiKhoan(obj[0],obj[1],obj[2]);
                tkList.add(tk);
            }
        } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    br.close();
                    fr.close();
                } catch (IOException ex) {

                }
            }
    }
    public void ArrayListToTable() {
        tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        for (int i = 0; i < tkList.size(); i++) {
            Vector v = new Vector();
            v.add(tkList.get(i).getType());
            v.add(tkList.get(i).getUserName());
            tableModel.addRow(v);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTaiKhoanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThayDoiQuyenTruyCap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
