/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLySinhVienUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author phamquanglong51
 */
public class SuaThongTinThiSinhUI extends javax.swing.JFrame {

    private String dataContructor;
    public String[] data;
    PreparedStatement pst = null;
    public SuaThongTinThiSinhUI(String dataContructor, String[] data){
        this.data = data;
        initComponents();
        
        try {
            Connection con = DBConnection.getConnection();
            String sql = "Select * from thisinh where SBD = "+dataContructor+"";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            this.dataContructor = dataContructor;
            if (rs.next()) {
                txtSoBaoDanh.setText(dataContructor);
                txtHoTen.setText(rs.getString(2));
                txtDiaChi.setText(rs.getString(3));
                cbUuTien.setSelectedItem(rs.getObject(4));
                cbKhoi.setSelectedItem(rs.getObject(5));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SuaThongTinThiSinhUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Creates new form SuaThongTinThiSinh
     */
    public SuaThongTinThiSinhUI() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCapNhat = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        sbd = new javax.swing.JLabel();
        hoten = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoBaoDanh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        cbUuTien = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbKhoi = new javax.swing.JComboBox<>();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sửa thông tin thí sinh");

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label.setText("Sửa thông tin thí sinh");

        sbd.setText("Số báo danh:");

        hoten.setText("Họ tên:");

        jLabel3.setText("Địa chỉ:");

        jLabel4.setText("Ưu tiên:");

        txtSoBaoDanh.setEnabled(false);

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        cbUuTien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Người dân tộc thiểu số (2 điểm)", "Thương bệnh binh (2 điểm)", "Quân nhân (2 điểm)", "Con của người hoạt động kháng chiến bị dị dạng, dị tật do hậu quả của chất độc hóa học (2 điểm)", "Người khuyết tật (1 điểm)", "Hộ khẩu thuộc vùng dân tộc, miền núi, biên giới, các xã đặc biệt khó khăn vùng bãi ngang ven biển và hải đảo (0.75 điểm)", "Khu vực nông thôn (0.5 điểm)", "Khu vực thị xã, thành phố trực thuộc tỉnh, các thị xã, huyện ngoại thành của thành phố trực thuộc Trung ương (0.25 điểm)" }));

        jLabel5.setText("Khối:");

        cbKhoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khối A", "Khối B", "Khối C", "Khối D" }));

        btnThoat.setText("Thoát");
        btnThoat.setActionCommand("");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoten)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(sbd)
                            .addComponent(jLabel5))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCapNhat)
                                        .addGap(279, 279, 279)
                                        .addComponent(btnThoat))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSoBaoDanh)
                                        .addComponent(txtDiaChi)
                                        .addComponent(txtHoTen)
                                        .addComponent(cbUuTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(label)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbd)
                    .addComponent(txtSoBaoDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoten)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbUuTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThoat))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JFrame frame = new JFrame();
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if (txtHoTen.getText().isEmpty())
            JOptionPane.showMessageDialog(frame, "Họ tên không được để trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else if (txtDiaChi.getText().isEmpty())
            JOptionPane.showMessageDialog(frame, "Địa chỉ không được bỏ trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else if (txtSoBaoDanh.getText().length() > 6)
            JOptionPane.showMessageDialog(frame, "Số báo danh phải gồm 6 chữ số", "Thông báo", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                Connection con = DBConnection.getConnection();
                String sql = "UPDATE `thisinh` SET `hoTen`= ?,`diaChi`= ?,`uuTien`= ?,`khoi`= ? WHERE SBD = ?";
                pst = con.prepareStatement(sql);

                pst.setString(1, txtHoTen.getText());
                pst.setString(2, txtDiaChi.getText());
                pst.setString(3, cbUuTien.getSelectedItem().toString());
                pst.setString(4, cbKhoi.getSelectedItem().toString());
                pst.setString(5, txtSoBaoDanh.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(frame, "Sửa thông tin thí sinh thành công!!!\n"
                    + "Số báo danh: "+txtSoBaoDanh.getText()+"\n"
                    + "Họ tên: "+txtHoTen.getText()+"\n"
                    + "Địa chỉ: "+txtDiaChi.getText()+"\n"
                    + "Ưu tiên: "+cbUuTien.getSelectedItem().toString()+"\n"
                    + "Khối: "+cbKhoi.getSelectedItem().toString()+"", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(ThemThiSinhMoiUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.dispose();
            new QLTS_Nhom3(data).setVisible(true);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QLTS_Nhom3(data).setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinThiSinhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinThiSinhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinThiSinhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinThiSinhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SuaThongTinThiSinhUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbKhoi;
    private javax.swing.JComboBox<String> cbUuTien;
    private javax.swing.JLabel hoten;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label;
    private javax.swing.JLabel sbd;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoBaoDanh;
    // End of variables declaration//GEN-END:variables
}
